### ISSUE TITLE
Process one-time charge for first payment in a subscription

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-authorize-net#1]
Right now we do an authorization which confuses many of our customers as they think it's a double charge.

https://github.com/restrictcontentpro/restrict-content-pro/issues/1723

**Comment by nosegraze** [comment]
This is in the `master` branch now and it's working well in my tests. The one thing I'm not sure about is this block we have now in the `process_webhooks()` method:

```php
if ( intval( $_POST['x_subscription_paynum'] ) > 1 || $is_trialing ) {

	// Renewal payment.
	$member->renew( $member->is_recurring() );
	do_action( 'rcp_webhook_recurring_payment_processed', $member, $payment_id, $this );

} elseif ( $member->is_recurring() ) {

	// Recurring profile first created.
	do_action( 'rcp_webhook_recurring_payment_profile_created', $member, $this );

}
```

Since the first payment is now a one-time transaction I _think_ we can remove this `if/else` block and always `renew()`... but I have no idea if Authorize.net sends a silent post when the subscription is first created, or if they don't send one out until the first _payment_ in a subscription is made. I'm thinking the latter, which means we can remove this `if/else` block.

I'd like to take this moment to thank Authorize.net for not sending silent posts in sandbox...... :P

**Comment by pippinsplugins** [comment]
I think we can probably remove it but might be worth sending an email to Authorize.net to ask. Maybe we'll get lucky and they'll reply.

**Comment by nosegraze** [comment]
I will contact them!
