### ISSUE TITLE
 Update MD5 transHash to use transHashSHA2

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/rcp-authorize-net#10]
We've received an email from Authorize.net stating they are phasing out the MD5 based `transHash` and moving to a SHA256 based `transHashSHA2`.

> The setting in the Merchant Interface which controls the MD5 Hash option will be removed by the end of January 2019, and the transHash element will stop returning values at a later date to be determined.  

Documentation for the upgrade to use transHashSHA2 can be found here: https://developer.authorize.net/support/hash_upgrade/?utm_campaign=19Q2%20MD5%20Hash%20EOL%20Partner&utm_medium=email&utm_source=Eloqua

**Comment by nosegraze** [comment]
Covered in this PR: #11
