### ISSUE TITLE
Check hash value in API responses during initial signup

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-authorize-net#12]
Value can be retrieved with:

```php
$transaction_response->getTransHashSha2();
```

**Comment by mintplugins** [comment]
I'm just waiting on a response here to hopefully track down my the hashes aren't matching up: 

https://community.developer.authorize.net/t5/Integration-and-Testing/Working-php-hash-verification/m-p/66394#M39941

**Comment by nosegraze** [comment]
PR: #17

**Comment by mintplugins** [comment]
Just following up here wayyyy late.

I was told the value has to be a decimal here, which did ultimately fix my hashes not validating:
https://github.com/restrictcontentpro/rcp-authorize-net/blob/master/includes/class-rcp-anet-payment-gateway.php#L228

https://community.developer.authorize.net/t5/Integration-and-Testing/Working-php-hash-verification/m-p/66394#M39941

Just leaving this comment here in case you run into this in RCP in the future.

**Comment by nosegraze** [comment]
Thanks for the heads up!
