### ISSUE TITLE
Listen for fraud webhooks (maybe)

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-authorize-net#13]
Phil is looking into this to see if it's feasible. We may want to listen out for the fraud webhooks and update the payment status accordingly (pending payment if held for review, complete it if approved, etc.).

**Comment by mintplugins** [comment]
For now I think we can leave the fraud webhooks alone, as Authorize.net prevents transactions for fraud entirely in my tests. Unless there's some case that isn't showing in their sandbox, the Fraud webhooks seem to be of little use.
