### ISSUE TITLE
Tweak a couple of values in is_webhook_valid

### ISSUE THREAD

**Issue by mintplugins** [restrictcontentpro/rcp-authorize-net#14]
There's a couple of tweaks I think that need to be made to the `is_webhook_valid` method. 

- `get_headers()` is not working for me. The results are blank. But `getallheaders()` works ¯\_(ツ)_/¯
- The name of the header sent by Authorize.net is `X-Anet-Signature` but the code is looking for `X-ANET-SIGNATURE`, which doesn't exist for my tests.

**Comment by nosegraze** [comment]
@mintplugins Are you using Apache? I don't think `getallheaders()` works with nginx because it's an alias for `apache_request_headers()`. It was added into PHP 7.3 but people not using that may have issues. See https://bugs.php.net/bug.php?id=62596

Do you see any potential issues with just using `$_SERVER['HTTP_X_ANET_SIGNATURE']` ?

**Comment by mintplugins** [comment]
@nosegraze For me this check was failing, resulting in in all webhooks failing:

https://github.com/restrictcontentpro/rcp-authorize-net/pull/15/files#diff-1c875ed52d276c67147ba847b74c5f90R706

**Comment by nosegraze** [comment]
@mintplugins I believe `$_SERVER` should have them in all uppercase. Is that not the case for you? Are you using apache or nginx?

**Comment by mintplugins** [comment]
@nosegraze I am using nginx.

**Comment by mintplugins** [comment]
Using $_SERVER did not work unfortunately. All my webhooks failed with that
<img width="601" alt="Screen Shot 2019-03-28 at 8 27 38 AM" src="https://user-images.githubusercontent.com/1638128/55157660-5f908700-5133-11e9-9054-9d1c62efde2e.png">

**Comment by mintplugins** [comment]
Going to dig in and try to find the cause here.

**Comment by nosegraze** [comment]
Weird. It works fine for me.

We could check if the `getallheaders()` function exists, if so, use that, and if not, use `$_SERVER` as a backup.

**Comment by mintplugins** [comment]
Actually, my bad. I missed adding `HTTP_` to the start. `$_SERVER['HTTP_X_ANET_SIGNATURE']` is working for me. I don't see a reason why that wouldn't work.
