### ISSUE TITLE
Signup fails if credit card expires before the start of the subscription

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-authorize-net#19]
This add-on moved to a new approach where the first payment is always a one-time transaction, then configures a subscription to be set up for the first renewal. This removed the need to perform a confusing card authorization and ensures that we can activate the subscription immediately because payment is received immediately.

However, this has introduced a new problem because Authorize.net prevents a subscription from being created if the supplied credit card will expire before the start of the subscription (even if the credit card is currently valid). They throw this error:

> Error code: E00018
> Error message: Credit Card expires before the start of the subscription.

For monthly memberships this may not be a huge deal, but if we're dealing with yearly memberships then I can see this becoming a common problem.

**Comment by nosegraze** [comment]
Gravity Forms had this problem too and ended up changing their flow: https://legacy.forums.gravityhelp.com/topic/authorizenet-arb I'm curious to find out how they handled it in the end.

**Comment by misulicus** [comment]
Can’t we compare the cards expiration date with the membership being purchased expiration date during checkout and if card expires before abort the registration ?
If not maybe we can get a copy of their plugins

**Comment by nosegraze** [comment]
Yes we could do that but it's not really a great user experience. I imagine this problem could happen a lot for yearly subscriptions, and customers still expect to be able to use their card for a signup if it hasn't expired yet.

I have a Gravity Forms license already so I might check out what they decided to do and see if I like it. Worst case scenario we go back to doing authorizations like we do now in RCP core.

**Comment by pippinsplugins** [comment]
@nosegraze try emailing Alex at Rocket Genius and see if he'll share what they did: alex@rocketgenius.com

**Comment by nosegraze** [comment]
PR:  #20

This reverts back to using authorizations for subscriptions like we do in core right now, with one small change: once the first subscription payment finally comes in the authorization gets voided. I'm hoping this might help clear up some of the confusion and concern about "double charging" that some customers have.

**Comment by dvrcthewrld** [comment]
I'm using this Authorize plugin now with 1yr subscriptions.  When I ran into this problem a couple weeks ago, I handled it by hooking into the auto_renew check function.  I check if the card expiration is more than 1 year out.  If it is, then I let the auto_renew be true.  If the card is going to expire within 12 months, then I simply changed the auto_renew to false.  That was sufficient for me.

Even if Auth would allow a subscription to be created using a card with a near expiration date, the user would need to update their payment method in the future, at or before the renewal date.  So, I may as well treat this as a non-recurring payment, and I'll hope that when they use a new card in 12 months they choose one with a far future expiration.

**Comment by nosegraze** [comment]
I'm glad to hear that works for you @dvrcthewrld ! Unfortunately I'm not sure we'll implement that officially simply because I suspect it would generate a lot of support tickets. I looked at other plugins use this method in the past, get a lot of support about it (even if just _"I have auto renewals enabled, why does this person not have auto renew on??"_), then change to something else because of it. I think for now we'll use the existing method that we're already using in RCP core right now, and we can consider spending more time looking at alternatives at a later date.
