### ISSUE TITLE
Use webhooks instead of silent post URL

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-authorize-net#3]
It looks like webhooks are replacing Silent Post.

Per their [documentation](https://support.authorize.net/authkb/index?page=content&id=A609):

> Important Note: While Silent Post is a supported service, we strongly recommend that you use Webhooks to receive transaction updates and other event notifications from the Authorize.Net Payment Gateway. Visit http://developer.authorize.net/api/reference/features/webhooks.html for more information on Webhooks

On the [webhook docs](http://developer.authorize.net/api/reference/features/webhooks.html) page:

> Note: Webhooks notifications replace the Silent Post method of receiving notifications.

At the moment I'm not clear on whether or not they send webhooks in sandbox mode, but if so that would be great since they do not send Silent Posts for sandbox transactions.

---

https://github.com/restrictcontentpro/restrict-content-pro/issues/1280

**Comment by nosegraze** [comment]
Copying from Slack:

It looks like they don't allow query strings in webhook URLs (WTF?) so we'll need a rewrite rule to make it `site.com/listener/authnet` or whatever instead of `site.com?listener=authnet`.

**Comment by nosegraze** [comment]
@misulicus Can you please start testing this? Basically sign up with every transaction type you can think of (signup fees, one-time payment, free trial, recurring subscription, recurring subscription with signup fee, etc.). This will eventually replace the Authorize.net gateway that's currently in core. A few notes:

- You need to test this with the `release/3.0` branch of RCP.
- You will need to get a "Signature Key" from Authorize.net. This is in Accounts > API Credentials & Keys.
- You will need to set up a webhook in Authorize.net. This is in Accounts > Webhooks. Set the URL to `https://yoursite.com/rcp-authorizenet-listener/`  . You can select `All Events`.
- Authorize.net hasn't yet been removed from RCP core, so this add-on will add the gateway listed as `Authorize.net (new)` in the admin area, and it will show as `Credit / Debit Card (new anet)` on the registration form.

Things to look for:

- [ ] When using a signup fee, ensure the correct amount with the fee is charged today.
- [ ] When setting up a subscription, Authorize.net will process a one-time transaction for the amount due today, then set up a subscription with a delayed start date to cover future payments. The start date should be the date that the next payment will be taken out.
- [ ] When signing up for a free trial, nothing should be charged today and the start date of the subscription in Authorize.net should be the same as the user's expiration date in RCP.

Let me know if you have any questions.

**Comment by nosegraze** [comment]
FYI, it's normal to get a few debug log entries like this:

```
2019-1-19 15:56:06 - Starting to process Authorize.net webhook.
2019-1-19 15:56:06 - NULL
2019-1-19 15:56:06 - Exiting Authorize.net webhook - invalid hash.
```

From what I can tell, Authorize.net occasionally sends an empty webhook. The important thing is that the successful ones also come in lol.

**Comment by misulicus** [comment]
Initial Payment looks good in Anet. 15$ price + 5$ signup fee:
https://www.screencast.com/t/qv1pylbV6Q2w

Subscription looks good too. Starts in 7 days:
https://www.screencast.com/t/SRGmPVuDDQ

Gateway Customer ID on the subscription in RCP is empty tho: https://www.screencast.com/t/hBeHSUNCWY

The ID i think its being passed correctly from Anet: https://www.screencast.com/t/Peogf8ANvF


Second test with trial:
Monthly sub with 7 days trial:
https://www.screencast.com/t/CM9jJkbSFIX

https://www.screencast.com/t/CM9jJkbSFIX
